version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: phoenix_project
      MYSQL_PASSWORD: ph8Enixx@482344
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .                  # Build from the Dockerfile in the current directory
    container_name: app_container
    ports:
      - "5000:5000"           # Expose port for the application if needed
    depends_on:
      - mysql                 # Ensure the app starts after MySQL

volumes:
  mysql_data:

